#!/bin/bash

# Only check package branches.
branch=$(git rev-parse --abbrev-ref HEAD)
if [[ "$branch" != "pipes"* ]]; then
    exit 0
fi

root_dir=$(git rev-parse --show-toplevel)
cd "$root_dir"

# Read hashes from existing PKGBUILD
source ./PKGBUILD
pkgbuild_hashes=(${sha256sums[@]})

# Get actual hashes according to makepkg
eval $(makepkg -g)
actual_hashes=(${sha256sums[@]})

# Compare the hashes
diff_output=$(diff -u \
    --label PKGBUILD --label actual \
    <(printf "%s\n" "${pkgbuild_hashes[@]}") \
    <(printf "%s\n" "${actual_hashes[@]}"))
if [[ $? != 0 ]]; then
    printf "PKGBUILD hashes do not match actual hashes. Diff:\n" >&2
    printf "%s\n" "$diff_output" >&2
    exit 1
fi

# Update .SRCINFO before each commit.
makepkg --printsrcinfo > .SRCINFO
git add ./.SRCINFO
